using SymbolExplorer.ViewModels;
using SymbolExplorerLib;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SymbolExplorer
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public ArchiveFileViewModel Archive = new ArchiveFileViewModel();

        public MainWindow()
        {
            InitializeComponent();
        }

        private void MenuItemOpen_Click(object sender, RoutedEventArgs e)
        {
            Microsoft.Win32.OpenFileDialog dlg = new Microsoft.Win32.OpenFileDialog();
            dlg.FileName = "";
            dlg.DefaultExt = ".lib";
            dlg.Filter = "Library Archives (.lib)|*.lib";

            Nullable<bool> result = dlg.ShowDialog();
            if (result == true)
            {
                LoadFile(dlg.FileName);
            }
        }

        private void MemberTree_SelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
        {

        }

        private void MenuItemAbout_Click(object sender, RoutedEventArgs e)
        {
            var assembly = Assembly.GetEntryAssembly();
            Version version = assembly.GetName().Version;
            string message = string.Format("SymbolExplorer {0}\n(c) 2013 Simon Stevenson", version.ToString());
            MessageBox.Show(message, "SymbolExplorer", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        public void LoadFile(string filePath)
        {
            FileStream s = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read);
            var file = ArchiveFile.FromStream(s);
            Archive.File = file;
            Archive.Name = System.IO.Path.GetFileName(filePath);

            this.DataContext = Archive;

            MemberTree.ItemsSource = Archive.Members;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            App app = App.Current as App;
            if (!string.IsNullOrEmpty(app.FileToOpen))
            {
                LoadFile(app.FileToOpen);
            }
        }

        private void symbolDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            string[] columnsToHide = { Utils.GetPropertyName<SymbolViewModel>(a => a.Name) };
            //foreach (var columnName in columnsToHide)
            //{
            //    var column = symbolDataGrid.Columns.Where(c => (c.Header.ToString() == columnName)).Single();
            //    column.Visibility = Visibility.Collapsed;
            //}

            string header = e.Column.Header.ToString();
            if (columnsToHide.Contains(header))
            {
                e.Column.Visibility = Visibility.Collapsed;
            }
        }

        private void symbolDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

            ContextMenu contextMenu = (ContextMenu)symbolDataGrid.FindResource("headerContextMenu");
            contextMenu.Items.Clear();
            foreach (var c in symbolDataGrid.Columns)
            {
                MenuItem item = new MenuItem();
                item.Header = c.Header;
                item.IsCheckable = true;
                item.IsChecked = (c.Visibility == Visibility.Visible);
                item.Checked += (object _sender, RoutedEventArgs _e) =>
                    {
                        c.Visibility = Visibility.Visible;
                    };
                item.Unchecked += (object _sender, RoutedEventArgs _e) =>
                    {
                        int visible = symbolDataGrid.Columns.Where(z => z.Visibility == Visibility.Visible).Count();
                        if (visible > 1)
                        {
                            c.Visibility = Visibility.Collapsed;
                        }
                        else { item.IsChecked = true; }
                    };
                contextMenu.Items.Add(item);
            }
        }
    }
}
