using SymbolExplorer.ViewModels;
using SymbolExplorer.Code;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using SymbolExplorer.Framework;

namespace SymbolExplorer
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void MenuItemOpen_Click(object sender, RoutedEventArgs e)
        {
            Microsoft.Win32.OpenFileDialog dlg = new Microsoft.Win32.OpenFileDialog();
            dlg.FileName = "";
            dlg.DefaultExt = ".lib";
            dlg.Filter = "Library Archives (.lib)|*.lib";

            Nullable<bool> result = dlg.ShowDialog();
            if (result == true)
            {
                switch(Path.GetExtension(dlg.FileName))
                {
                case ".lib":
                    Model.LoadFile(dlg.FileName);
                    break;

                case ".a":
                    Model.LoadFileA(dlg.FileName);
                    break;
                }

                TreeViewItem item = new TreeViewItem();
                item.Header = Model.ArchiveFile.Name;
                item.ItemsSource = Model.ArchiveFile.Members;
                item.ItemTemplate = (DataTemplate)FindResource("ArchiveMemberViewTemplate");
                item.ExpandSubtree();

                MemberTree.Items.Add(item);
            }
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            App app = App.Current as App;
            if (!string.IsNullOrEmpty(app.FileToOpen))
            {
                Model.LoadFile(app.FileToOpen);
            }
        }

        private void symbolDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

            ContextMenu contextMenu = (ContextMenu)symbolDataGrid.FindResource("headerContextMenu");
            contextMenu.Items.Clear();
            foreach (var c in symbolDataGrid.Columns)
            {
                MenuItem item = new MenuItem();
                item.Header = c.Header;
                item.IsCheckable = true;
                item.IsChecked = (c.Visibility == Visibility.Visible);
                item.Checked += (object _sender, RoutedEventArgs _e) =>
                    {
                        c.Visibility = Visibility.Visible;
                    };
                item.Unchecked += (object _sender, RoutedEventArgs _e) =>
                    {
                        int visible = symbolDataGrid.Columns.Where(z => z.Visibility == Visibility.Visible).Count();
                        if (visible > 1)
                        {
                            c.Visibility = Visibility.Collapsed;
                        }
                        else { item.IsChecked = true; }
                    };
                contextMenu.Items.Add(item);
            }
        }

        private void toggleLinkerSymbols_ToggleChecked(object sender, RoutedEventArgs e)
        {
            var source = symbolDataGrid.ItemsSource as ListCollectionView;
            if (source != null)
            {
                source.Refresh();
            }
        }
    }
}
