Set-Alias -Name AS-UpdateAutoScalingGroup -Value Update-ASAutoScalingGroup
Set-Alias -Name Describe-ASLaunchConfigurations -Value Get-ASLaunchConfiguration
Set-Alias -Name AS-DescribeLaunchConfigurations -Value Get-ASLaunchConfiguration
Set-Alias -Name Describe-ASAdjustmentTypes -Value Get-ASAdjustmentType
Set-Alias -Name AS-DescribeAdjustmentTypes -Value Get-ASAdjustmentType
Set-Alias -Name Describe-ASScheduledActions -Value Get-ASScheduledAction
Set-Alias -Name AS-DescribeScheduledActions -Value Get-ASScheduledAction
Set-Alias -Name Put-ASScheduledUpdateGroupAction -Value Write-ASScheduledUpdateGroupAction
Set-Alias -Name AS-PutScheduledUpdateGroupAction -Value Write-ASScheduledUpdateGroupAction
Set-Alias -Name Describe-ASMetricCollectionTypes -Value Get-ASMetricCollectionType
Set-Alias -Name AS-DescribeMetricCollectionTypes -Value Get-ASMetricCollectionType
Set-Alias -Name AS-SetDesiredCapacity -Value Set-ASDesiredCapacity
Set-Alias -Name Terminate-ASInstanceInAutoScalingGroup -Value Stop-ASInstanceInAutoScalingGroup
Set-Alias -Name AS-TerminateInstanceInAutoScalingGroup -Value Stop-ASInstanceInAutoScalingGroup
Set-Alias -Name Describe-ASAutoScalingGroups -Value Get-ASAutoScalingGroup
Set-Alias -Name AS-DescribeAutoScalingGroups -Value Get-ASAutoScalingGroup
Set-Alias -Name AS-EnableMetricsCollection -Value Enable-ASMetricsCollection
Set-Alias -Name Resume-ASProcesses -Value Resume-ASProcess
Set-Alias -Name AS-ResumeProcesses -Value Resume-ASProcess
Set-Alias -Name Delete-ASLaunchConfiguration -Value Remove-ASLaunchConfiguration
Set-Alias -Name AS-DeleteLaunchConfiguration -Value Remove-ASLaunchConfiguration
Set-Alias -Name Describe-ASPolicies -Value Get-ASPolicy
Set-Alias -Name AS-DescribePolicies -Value Get-ASPolicy
Set-Alias -Name Describe-ASScalingProcessTypes -Value Get-ASScalingProcessType
Set-Alias -Name AS-DescribeScalingProcessTypes -Value Get-ASScalingProcessType
Set-Alias -Name Create-ASAutoScalingGroup -Value New-ASAutoScalingGroup
Set-Alias -Name AS-CreateAutoScalingGroup -Value New-ASAutoScalingGroup
Set-Alias -Name Describe-ASScalingActivities -Value Get-ASScalingActivity
Set-Alias -Name AS-DescribeScalingActivities -Value Get-ASScalingActivity
Set-Alias -Name Describe-ASNotificationConfigurations -Value Get-ASNotificationConfiguration
Set-Alias -Name AS-DescribeNotificationConfigurations -Value Get-ASNotificationConfiguration
Set-Alias -Name Describe-ASTerminationPolicyTypes -Value Get-ASTerminationPolicyType
Set-Alias -Name AS-DescribeTerminationPolicyTypes -Value Get-ASTerminationPolicyType
Set-Alias -Name Describe-ASTags -Value Get-ASTag
Set-Alias -Name AS-DescribeTags -Value Get-ASTag
Set-Alias -Name Delete-ASTags -Value Remove-ASTag
Set-Alias -Name AS-DeleteTags -Value Remove-ASTag
Set-Alias -Name Execute-ASPolicy -Value Start-ASPolicy
Set-Alias -Name AS-ExecutePolicy -Value Start-ASPolicy
Set-Alias -Name Put-ASScalingPolicy -Value Write-ASScalingPolicy
Set-Alias -Name AS-PutScalingPolicy -Value Write-ASScalingPolicy
Set-Alias -Name Put-ASNotificationConfiguration -Value Write-ASNotificationConfiguration
Set-Alias -Name AS-PutNotificationConfiguration -Value Write-ASNotificationConfiguration
Set-Alias -Name Delete-ASPolicy -Value Remove-ASPolicy
Set-Alias -Name AS-DeletePolicy -Value Remove-ASPolicy
Set-Alias -Name Delete-ASNotificationConfiguration -Value Remove-ASNotificationConfiguration
Set-Alias -Name AS-DeleteNotificationConfiguration -Value Remove-ASNotificationConfiguration
Set-Alias -Name Delete-ASScheduledAction -Value Remove-ASScheduledAction
Set-Alias -Name AS-DeleteScheduledAction -Value Remove-ASScheduledAction
Set-Alias -Name AS-SetInstanceHealth -Value Set-ASInstanceHealth
Set-Alias -Name Describe-ASAutoScalingNotificationTypes -Value Get-ASAutoScalingNotificationType
Set-Alias -Name AS-DescribeAutoScalingNotificationTypes -Value Get-ASAutoScalingNotificationType
Set-Alias -Name AS-CreateOrUpdateTags -Value Set-ASTag
Set-Alias -Name Suspend-ASProcesses -Value Suspend-ASProcess
Set-Alias -Name AS-SuspendProcesses -Value Suspend-ASProcess
Set-Alias -Name Describe-ASAutoScalingInstances -Value Get-ASAutoScalingInstance
Set-Alias -Name AS-DescribeAutoScalingInstances -Value Get-ASAutoScalingInstance
Set-Alias -Name Create-ASLaunchConfiguration -Value New-ASLaunchConfiguration
Set-Alias -Name AS-CreateLaunchConfiguration -Value New-ASLaunchConfiguration
Set-Alias -Name Delete-ASAutoScalingGroup -Value Remove-ASAutoScalingGroup
Set-Alias -Name AS-DeleteAutoScalingGroup -Value Remove-ASAutoScalingGroup
Set-Alias -Name AS-DisableMetricsCollection -Value Disable-ASMetricsCollection
Set-Alias -Name Describe-EBApplications -Value Get-EBApplication
Set-Alias -Name EB-DescribeApplications -Value Get-EBApplication
Set-Alias -Name EB-RebuildEnvironment -Value Start-EBEnvironmentRebuild
Set-Alias -Name Describe-EBEvents -Value Get-EBEvent
Set-Alias -Name EB-DescribeEvents -Value Get-EBEvent
Set-Alias -Name Check-EBDNSAvailability -Value Get-EBDNSAvailability
Set-Alias -Name EB-CheckDNSAvailability -Value Get-EBDNSAvailability
Set-Alias -Name Describe-EBConfigurationOptions -Value Get-EBConfigurationOption
Set-Alias -Name EB-DescribeConfigurationOptions -Value Get-EBConfigurationOption
Set-Alias -Name Delete-EBConfigurationTemplate -Value Remove-EBConfigurationTemplate
Set-Alias -Name EB-DeleteConfigurationTemplate -Value Remove-EBConfigurationTemplate
Set-Alias -Name Create-EBEnvironment -Value New-EBEnvironment
Set-Alias -Name EB-CreateEnvironment -Value New-EBEnvironment
Set-Alias -Name Create-EBStorageLocation -Value New-EBStorageLocation
Set-Alias -Name EB-CreateStorageLocation -Value New-EBStorageLocation
Set-Alias -Name EB-RequestEnvironmentInfo -Value Request-EBEnvironmentInfo
Set-Alias -Name Create-EBApplicationVersion -Value New-EBApplicationVersion
Set-Alias -Name EB-CreateApplicationVersion -Value New-EBApplicationVersion
Set-Alias -Name Delete-EBApplicationVersion -Value Remove-EBApplicationVersion
Set-Alias -Name EB-DeleteApplicationVersion -Value Remove-EBApplicationVersion
Set-Alias -Name Describe-EBApplicationVersions -Value Get-EBApplicationVersion
Set-Alias -Name EB-DescribeApplicationVersions -Value Get-EBApplicationVersion
Set-Alias -Name Delete-EBApplication -Value Remove-EBApplication
Set-Alias -Name EB-DeleteApplication -Value Remove-EBApplication
Set-Alias -Name EB-UpdateApplicationVersion -Value Update-EBApplicationVersion
Set-Alias -Name Create-EBApplication -Value New-EBApplication
Set-Alias -Name EB-CreateApplication -Value New-EBApplication
Set-Alias -Name Swap-EBEnvironmentCNAMEs -Value Set-EBEnvironmentCNAME
Set-Alias -Name EB-SwapEnvironmentCNAMEs -Value Set-EBEnvironmentCNAME
Set-Alias -Name EB-UpdateConfigurationTemplate -Value Update-EBConfigurationTemplate
Set-Alias -Name Retrieve-EBEnvironmentInfo -Value Get-EBEnvironmentInfo
Set-Alias -Name EB-RetrieveEnvironmentInfo -Value Get-EBEnvironmentInfo
Set-Alias -Name List-EBAvailableSolutionStacks -Value Get-EBAvailableSolutionStack
Set-Alias -Name EB-ListAvailableSolutionStacks -Value Get-EBAvailableSolutionStack
Set-Alias -Name EB-UpdateApplication -Value Update-EBApplication
Set-Alias -Name Describe-EBEnvironments -Value Get-EBEnvironment
Set-Alias -Name EB-DescribeEnvironments -Value Get-EBEnvironment
Set-Alias -Name Describe-EBEnvironmentResources -Value Get-EBEnvironmentResource
Set-Alias -Name EB-DescribeEnvironmentResources -Value Get-EBEnvironmentResource
Set-Alias -Name Terminate-EBEnvironment -Value Stop-EBEnvironment
Set-Alias -Name EB-TerminateEnvironment -Value Stop-EBEnvironment
Set-Alias -Name Validate-EBConfigurationSettings -Value Test-EBConfigurationSetting
Set-Alias -Name EB-ValidateConfigurationSettings -Value Test-EBConfigurationSetting
Set-Alias -Name EB-RestartAppServer -Value Restart-EBAppServer
Set-Alias -Name Delete-EBEnvironmentConfiguration -Value Remove-EBEnvironmentConfiguration
Set-Alias -Name EB-DeleteEnvironmentConfiguration -Value Remove-EBEnvironmentConfiguration
Set-Alias -Name EB-UpdateEnvironment -Value Update-EBEnvironment
Set-Alias -Name Create-EBConfigurationTemplate -Value New-EBConfigurationTemplate
Set-Alias -Name EB-CreateConfigurationTemplate -Value New-EBConfigurationTemplate
Set-Alias -Name Describe-EBConfigurationSettings -Value Get-EBConfigurationSetting
Set-Alias -Name EB-DescribeConfigurationSettings -Value Get-EBConfigurationSetting
Set-Alias -Name CFN-ValidateTemplate -Value Test-CFNTemplate
Set-Alias -Name Validate-CFNTemplate -Value Test-CFNTemplate
Set-Alias -Name CFN-DescribeStacks -Value Get-CFNStack
Set-Alias -Name CFN-GetTemplate -Value Get-CFNTemplate
Set-Alias -Name CFN-ListStacks -Value Get-CFNStackSummary
Set-Alias -Name CFN-CreateStack -Value New-CFNStack
Set-Alias -Name CFN-EstimateTemplateCost -Value Measure-CFNTemplateCost
Set-Alias -Name Estimate-CFNTemplateCost -Value Measure-CFNTemplateCost
Set-Alias -Name CFN-DescribeStackEvents -Value Get-CFNStackEvent
Set-Alias -Name CFN-DescribeStackResource -Value Get-CFNStackResource
Set-Alias -Name CFN-CancelUpdateStack -Value Stop-CFNUpdateStack
Set-Alias -Name CFN-DeleteStack -Value Remove-CFNStack
Set-Alias -Name CFN-ListStackResources -Value Get-CFNStackResourceSummary
Set-Alias -Name CFN-DescribeStackResources -Value Get-CFNStackResources
Set-Alias -Name CFN-UpdateStack -Value Update-CFNStack
Set-Alias -Name List-CFNStacks -Value Get-CFNStackSummaries
Set-Alias -Name List-CFNStackResources -Value Get-CFNStackResourceSummaries
Set-Alias -Name CF-CreateInvalidation -Value New-CFInvalidation
Set-Alias -Name CF-ListCloudFrontOriginAccessIdentities -Value Get-CFCloudFrontOriginAccessIdentities
Set-Alias -Name CF-UpdateCloudFrontOriginAccessIdentity -Value Update-CFCloudFrontOriginAccessIdentity
Set-Alias -Name CF-GetStreamingDistribution -Value Get-CFStreamingDistribution
Set-Alias -Name CF-DeleteDistribution -Value Remove-CFDistribution
Set-Alias -Name CF-GetDistributionConfig -Value Get-CFDistributionConfig
Set-Alias -Name CF-UpdateDistribution -Value Update-CFDistribution
Set-Alias -Name CF-CreateDistribution -Value New-CFDistribution
Set-Alias -Name CF-GetCloudFrontOriginAccessIdentityConfig -Value Get-CFCloudFrontOriginAccessIdentityConfig
Set-Alias -Name CF-ListInvalidations -Value Get-CFInvalidations
Set-Alias -Name CF-ListDistributions -Value Get-CFDistributions
Set-Alias -Name CF-GetStreamingDistributionConfig -Value Get-CFStreamingDistributionConfig
Set-Alias -Name CF-GetDistribution -Value Get-CFDistribution
Set-Alias -Name CF-DeleteStreamingDistribution -Value Remove-CFStreamingDistribution
Set-Alias -Name CF-CreateCloudFrontOriginAccessIdentity -Value New-CFCloudFrontOriginAccessIdentity
Set-Alias -Name CF-ListStreamingDistributions -Value Get-CFStreamingDistributions
Set-Alias -Name CF-DeleteCloudFrontOriginAccessIdentity -Value Remove-CFCloudFrontOriginAccessIdentity
Set-Alias -Name CF-UpdateStreamingDistribution -Value Update-CFStreamingDistribution
Set-Alias -Name CF-GetInvalidation -Value Get-CFInvalidation
Set-Alias -Name CF-CreateStreamingDistribution -Value New-CFStreamingDistribution
Set-Alias -Name CF-GetCloudFrontOriginAccessIdentity -Value Get-CFCloudFrontOriginAccessIdentity
Set-Alias -Name CS-UpdateDefaultSearchField -Value Update-CSDefaultSearchField
Set-Alias -Name CS-DeleteRankExpression -Value Remove-CSRankExpression
Set-Alias -Name CS-DescribeRankExpressions -Value Get-CSRankExpression
Set-Alias -Name CS-CreateDomain -Value New-CSDomain
Set-Alias -Name CS-UpdateServiceAccessPolicies -Value Update-CSServiceAccessPolicy
Set-Alias -Name CS-DefineIndexField -Value Set-CSIndexField
Set-Alias -Name Define-CSIndexField -Value Set-CSIndexField
Set-Alias -Name CS-DefineRankExpression -Value Set-CSRankExpression
Set-Alias -Name CS-DescribeSynonymOptions -Value Get-CSSynonymOption
Set-Alias -Name CS-DescribeStopwordOptions -Value Get-CSStopwordOption
Set-Alias -Name CS-DeleteDomain -Value Remove-CSDomain
Set-Alias -Name CS-DescribeServiceAccessPolicies -Value Get-CSServiceAccessPolicy
Set-Alias -Name CS-DescribeDefaultSearchField -Value Get-CSDefaultSearchField
Set-Alias -Name CS-UpdateStopwordOptions -Value Update-CSStopwordOption
Set-Alias -Name CS-UpdateSynonymOptions -Value Update-CSSynonymOption
Set-Alias -Name CS-UpdateStemmingOptions -Value Update-CSStemmingOption
Set-Alias -Name CS-DescribeStemmingOptions -Value Get-CSStemmingOption
Set-Alias -Name CS-DescribeDomains -Value Get-CSDomain
Set-Alias -Name CS-IndexDocuments -Value Start-CSIndex
Set-Alias -Name Index-CSDocuments -Value Start-CSIndex
Set-Alias -Name CS-DescribeIndexFields -Value Get-CSIndexField
Set-Alias -Name CS-DeleteIndexField -Value Remove-CSIndexField
Set-Alias -Name CW-PutMetricAlarm -Value Write-CWMetricAlarm
Set-Alias -Name CW-PutMetricData -Value Write-CWMetricData
Set-Alias -Name CW-ListMetrics -Value Get-CWMetrics
Set-Alias -Name CW-GetMetricStatistics -Value Get-CWMetricStatistics
Set-Alias -Name CW-DisableAlarmActions -Value Disable-CWAlarmAction
Set-Alias -Name CW-DescribeAlarms -Value Get-CWAlarm
Set-Alias -Name CW-DescribeAlarmsForMetric -Value Get-CWAlarmForMetric
Set-Alias -Name CW-DescribeAlarmHistory -Value Get-CWAlarmHistory
Set-Alias -Name CW-EnableAlarmActions -Value Enable-CWAlarmAction
Set-Alias -Name CW-DeleteAlarms -Value Remove-CWAlarm
Set-Alias -Name CW-SetAlarmState -Value Set-CWAlarmState
Set-Alias -Name DP-ActivatePipeline -Value Enable-DPPipeline
Set-Alias -Name DP-ListPipelines -Value Get-DPPipeline
Set-Alias -Name DP-ReportTaskProgress -Value Update-DPTaskProgress
Set-Alias -Name DP-ValidatePipelineDefinition -Value Test-DPPipelineDefinition
Set-Alias -Name DP-PollForTask -Value Get-DPTask
Set-Alias -Name DP-QueryObjects -Value Find-DPObject
Set-Alias -Name DP-SetStatus -Value Set-DPStatus
Set-Alias -Name DP-DeletePipeline -Value Remove-DPPipeline
Set-Alias -Name DP-GetPipelineDefinition -Value Get-DPPipelineDefinition
Set-Alias -Name DP-SetTaskStatus -Value Set-DPTaskStatus
Set-Alias -Name DP-EvaluateExpression -Value Invoke-DPExpression
Set-Alias -Name DP-DescribePipelines -Value Get-DPPipelineDescription
Set-Alias -Name DP-CreatePipeline -Value New-DPPipeline
Set-Alias -Name DP-DescribeObjects -Value Get-DPObject
Set-Alias -Name DP-ReportTaskRunnerHeartbeat -Value Update-DPTaskRunnerHeartbeat
Set-Alias -Name DP-PutPipelineDefinition -Value Write-DPPipelineDefinition
Set-Alias -Name DC-DescribeVirtualInterfaces -Value Get-DCVirtualInterface
Set-Alias -Name DC-DescribeVirtualGateways -Value Get-DCVirtualGateway
Set-Alias -Name DC-DescribeConnectionDetail -Value Get-DCConnectionDetail
Set-Alias -Name DC-DescribeOfferings -Value Get-DCOffering
Set-Alias -Name DC-DescribeConnections -Value Get-DCConnection
Set-Alias -Name DC-DescribeOfferingDetail -Value Get-DCOfferingDetail
Set-Alias -Name DC-DeleteConnection -Value Remove-DCConnection
Set-Alias -Name DC-CreateConnection -Value New-DCConnection
Set-Alias -Name DC-CreatePrivateVirtualInterface -Value New-DCPrivateVirtualInterface
Set-Alias -Name DC-DeleteVirtualInterface -Value Remove-DCVirtualInterface
Set-Alias -Name DC-CreatePublicVirtualInterface -Value New-DCPublicVirtualInterface
Set-Alias -Name Create-EC2DhcpOptions -Value New-EC2DhcpOption
Set-Alias -Name EC2-CreateDhcpOptions -Value New-EC2DhcpOption
Set-Alias -Name Request-EC2SpotInstances -Value Request-EC2SpotInstance
Set-Alias -Name EC2-RequestSpotInstances -Value Request-EC2SpotInstance
Set-Alias -Name Describe-EC2SpotInstanceRequests -Value Get-EC2SpotInstanceRequest
Set-Alias -Name EC2-DescribeSpotInstanceRequests -Value Get-EC2SpotInstanceRequest
Set-Alias -Name Cancel-EC2SpotInstanceRequests -Value Stop-EC2SpotInstanceRequest
Set-Alias -Name EC2-CancelSpotInstanceRequests -Value Stop-EC2SpotInstanceRequest
Set-Alias -Name Describe-EC2SpotPriceHistory -Value Get-EC2SpotPriceHistory
Set-Alias -Name EC2-DescribeSpotPriceHistory -Value Get-EC2SpotPriceHistory
Set-Alias -Name Create-EC2SpotDatafeedSubscription -Value New-EC2SpotDatafeedSubscription
Set-Alias -Name EC2-CreateSpotDatafeedSubscription -Value New-EC2SpotDatafeedSubscription
Set-Alias -Name Describe-EC2SpotDatafeedSubscription -Value Get-EC2SpotDatafeedSubscription
Set-Alias -Name EC2-DescribeSpotDatafeedSubscription -Value Get-EC2SpotDatafeedSubscription
Set-Alias -Name Delete-EC2SpotDatafeedSubscription -Value Remove-EC2SpotDatafeedSubscription
Set-Alias -Name EC2-DeleteSpotDatafeedSubscription -Value Remove-EC2SpotDatafeedSubscription
Set-Alias -Name Cancel-EC2ConversionTask -Value Stop-EC2ConversionTask
Set-Alias -Name EC2-CancelConversionTask -Value Stop-EC2ConversionTask
Set-Alias -Name Describe-EC2ConversionTasks -Value Get-EC2ConversionTask
Set-Alias -Name EC2-DescribeConversionTasks -Value Get-EC2ConversionTask
Set-Alias -Name EC2-ImportInstance -Value Import-EC2Instance
Set-Alias -Name EC2-ImportVolume -Value Import-EC2Volume
Set-Alias -Name Authorize-EC2SecurityGroupEgress -Value Grant-EC2SecurityGroupEgress
Set-Alias -Name EC2-AuthorizeSecurityGroupEgress -Value Grant-EC2SecurityGroupEgress
Set-Alias -Name EC2-RevokeSecurityGroupEgress -Value Revoke-EC2SecurityGroupEgress
Set-Alias -Name Create-EC2InternetGateway -Value New-EC2InternetGateway
Set-Alias -Name EC2-CreateInternetGateway -Value New-EC2InternetGateway
Set-Alias -Name Describe-EC2InternetGateways -Value Get-EC2InternetGateway
Set-Alias -Name EC2-DescribeInternetGateways -Value Get-EC2InternetGateway
Set-Alias -Name Delete-EC2InternetGateway -Value Remove-EC2InternetGateway
Set-Alias -Name EC2-DeleteInternetGateway -Value Remove-EC2InternetGateway
Set-Alias -Name Attach-EC2InternetGateway -Value Add-EC2InternetGateway
Set-Alias -Name EC2-AttachInternetGateway -Value Add-EC2InternetGateway
Set-Alias -Name Detach-EC2InternetGateway -Value Dismount-EC2InternetGateway
Set-Alias -Name EC2-DetachInternetGateway -Value Dismount-EC2InternetGateway
Set-Alias -Name Create-EC2RouteTable -Value New-EC2RouteTable
Set-Alias -Name EC2-CreateRouteTable -Value New-EC2RouteTable
Set-Alias -Name Describe-EC2RouteTables -Value Get-EC2RouteTable
Set-Alias -Name EC2-DescribeRouteTables -Value Get-EC2RouteTable
Set-Alias -Name Delete-EC2RouteTable -Value Remove-EC2RouteTable
Set-Alias -Name EC2-DeleteRouteTable -Value Remove-EC2RouteTable
Set-Alias -Name Associate-EC2RouteTable -Value Register-EC2RouteTable
Set-Alias -Name EC2-AssociateRouteTable -Value Register-EC2RouteTable
Set-Alias -Name Replace-EC2RouteTableAssociation -Value Set-EC2RouteTableAssociation
Set-Alias -Name EC2-ReplaceRouteTableAssociation -Value Set-EC2RouteTableAssociation
Set-Alias -Name Disassociate-EC2RouteTable -Value Unregister-EC2RouteTable
Set-Alias -Name EC2-DisassociateRouteTable -Value Unregister-EC2RouteTable
Set-Alias -Name Create-EC2Route -Value New-EC2Route
Set-Alias -Name EC2-CreateRoute -Value New-EC2Route
Set-Alias -Name Replace-EC2Route -Value Set-EC2Route
Set-Alias -Name EC2-ReplaceRoute -Value Set-EC2Route
Set-Alias -Name Delete-EC2Route -Value Remove-EC2Route
Set-Alias -Name EC2-DeleteRoute -Value Remove-EC2Route
Set-Alias -Name Create-EC2NetworkAcl -Value New-EC2NetworkAcl
Set-Alias -Name EC2-CreateNetworkAcl -Value New-EC2NetworkAcl
Set-Alias -Name Describe-EC2NetworkAcls -Value Get-EC2NetworkAcl
Set-Alias -Name EC2-DescribeNetworkAcls -Value Get-EC2NetworkAcl
Set-Alias -Name Delete-EC2NetworkAcl -Value Remove-EC2NetworkAcl
Set-Alias -Name EC2-DeleteNetworkAcl -Value Remove-EC2NetworkAcl
Set-Alias -Name Replace-EC2NetworkAclAssociation -Value Set-EC2NetworkAclAssociation
Set-Alias -Name EC2-ReplaceNetworkAclAssociation -Value Set-EC2NetworkAclAssociation
Set-Alias -Name Create-EC2NetworkAclEntry -Value New-EC2NetworkAclEntry
Set-Alias -Name EC2-CreateNetworkAclEntry -Value New-EC2NetworkAclEntry
Set-Alias -Name Replace-EC2NetworkAclEntry -Value Set-EC2NetworkAclEntry
Set-Alias -Name EC2-ReplaceNetworkAclEntry -Value Set-EC2NetworkAclEntry
Set-Alias -Name Delete-EC2NetworkAclEntry -Value Remove-EC2NetworkAclEntry
Set-Alias -Name EC2-DeleteNetworkAclEntry -Value Remove-EC2NetworkAclEntry
Set-Alias -Name Attach-EC2NetworkInterface -Value Add-EC2NetworkInterface
Set-Alias -Name EC2-AttachNetworkInterface -Value Add-EC2NetworkInterface
Set-Alias -Name Create-EC2NetworkInterface -Value New-EC2NetworkInterface
Set-Alias -Name EC2-CreateNetworkInterface -Value New-EC2NetworkInterface
Set-Alias -Name Delete-EC2NetworkInterface -Value Remove-EC2NetworkInterface
Set-Alias -Name EC2-DeleteNetworkInterface -Value Remove-EC2NetworkInterface
Set-Alias -Name Describe-EC2NetworkInterfaceAttribute -Value Get-EC2NetworkInterfaceAttribute
Set-Alias -Name EC2-DescribeNetworkInterfaceAttribute -Value Get-EC2NetworkInterfaceAttribute
Set-Alias -Name Describe-EC2NetworkInterfaces -Value Get-EC2NetworkInterface
Set-Alias -Name EC2-DescribeNetworkInterfaces -Value Get-EC2NetworkInterface
Set-Alias -Name Detach-EC2NetworkInterface -Value Dismount-EC2NetworkInterface
Set-Alias -Name EC2-DetachNetworkInterface -Value Dismount-EC2NetworkInterface
Set-Alias -Name Modify-EC2NetworkInterfaceAttribute -Value Edit-EC2NetworkInterfaceAttribute
Set-Alias -Name EC2-ModifyNetworkInterfaceAttribute -Value Edit-EC2NetworkInterfaceAttribute
Set-Alias -Name EC2-ResetNetworkInterfaceAttribute -Value Reset-EC2NetworkInterfaceAttribute
Set-Alias -Name Describe-EC2VolumeStatus -Value Get-EC2VolumeStatus
Set-Alias -Name EC2-DescribeVolumeStatus -Value Get-EC2VolumeStatus
Set-Alias -Name EC2-EnableVolumeIO -Value Enable-EC2VolumeIO
Set-Alias -Name Modify-EC2VolumeAttribute -Value Edit-EC2VolumeAttribute
Set-Alias -Name EC2-ModifyVolumeAttribute -Value Edit-EC2VolumeAttribute
Set-Alias -Name Describe-EC2VolumeAttribute -Value Get-EC2VolumeAttribute
Set-Alias -Name EC2-DescribeVolumeAttribute -Value Get-EC2VolumeAttribute
Set-Alias -Name Assign-EC2PrivateIpAddresses -Value Register-EC2PrivateIpAddresse
Set-Alias -Name EC2-AssignPrivateIpAddresses -Value Register-EC2PrivateIpAddresse
Set-Alias -Name Unassign-EC2PrivateIpAddresses -Value Unregister-EC2PrivateIpAddresse
Set-Alias -Name EC2-UnassignPrivateIpAddresses -Value Unregister-EC2PrivateIpAddresse
Set-Alias -Name Create-EC2VpnConnectionRoute -Value New-EC2VpnConnectionRoute
Set-Alias -Name EC2-CreateVpnConnectionRoute -Value New-EC2VpnConnectionRoute
Set-Alias -Name Delete-EC2VpnConnectionRoute -Value Remove-EC2VpnConnectionRoute
Set-Alias -Name EC2-DeleteVpnConnectionRoute -Value Remove-EC2VpnConnectionRoute
Set-Alias -Name EC2-EnableVGWRoutePropagation -Value Enable-EC2VGWRoutePropagation
Set-Alias -Name EC2-DisableVGWRoutePropagation -Value Disable-EC2VGWRoutePropagation
Set-Alias -Name Cancel-EC2ReservedInstancesListing -Value Stop-EC2ReservedInstancesListing
Set-Alias -Name EC2-CancelReservedInstancesListing -Value Stop-EC2ReservedInstancesListing
Set-Alias -Name Create-EC2ReservedInstancesListing -Value New-EC2ReservedInstancesListing
Set-Alias -Name EC2-CreateReservedInstancesListing -Value New-EC2ReservedInstancesListing
Set-Alias -Name Describe-EC2ReservedInstancesListings -Value Get-EC2ReservedInstancesListing
Set-Alias -Name EC2-DescribeReservedInstancesListings -Value Get-EC2ReservedInstancesListing
Set-Alias -Name EC2-CopySnapshot -Value Copy-EC2Snapshot
Set-Alias -Name Describe-EC2VpcAttributes -Value Get-EC2VpcAttributes
Set-Alias -Name EC2-DescribeVpcAttributes -Value Get-EC2VpcAttributes
Set-Alias -Name Modify-EC2VpcAttributes -Value Edit-EC2VpcAttributes
Set-Alias -Name EC2-ModifyVpcAttributes -Value Edit-EC2VpcAttributes
Set-Alias -Name Describe-EC2AccountAttributes -Value Get-EC2AccountAttributes
Set-Alias -Name EC2-DescribeAccountAttributes -Value Get-EC2AccountAttributes
Set-Alias -Name Activate-EC2License -Value Enable-EC2License
Set-Alias -Name EC2-ActivateLicense -Value Enable-EC2License
Set-Alias -Name Allocate-EC2Address -Value New-EC2Address
Set-Alias -Name EC2-AllocateAddress -Value New-EC2Address
Set-Alias -Name Associate-EC2Address -Value Register-EC2Address
Set-Alias -Name EC2-AssociateAddress -Value Register-EC2Address
Set-Alias -Name Attach-EC2Volume -Value Add-EC2Volume
Set-Alias -Name EC2-AttachVolume -Value Add-EC2Volume
Set-Alias -Name Authorize-EC2SecurityGroupIngress -Value Grant-EC2SecurityGroupIngress
Set-Alias -Name EC2-AuthorizeSecurityGroupIngress -Value Grant-EC2SecurityGroupIngress
Set-Alias -Name EC2-BundleInstance -Value New-EC2InstanceBundle
Set-Alias -Name Cancel-EC2BundleTask -Value Stop-EC2BundleTask
Set-Alias -Name EC2-CancelBundleTask -Value Stop-EC2BundleTask
Set-Alias -Name EC2-ConfirmProductInstance -Value Confirm-EC2ProductInstance
Set-Alias -Name Create-EC2Image -Value New-EC2Image
Set-Alias -Name EC2-CreateImage -Value New-EC2Image
Set-Alias -Name Create-EC2KeyPair -Value New-EC2KeyPair
Set-Alias -Name EC2-CreateKeyPair -Value New-EC2KeyPair
Set-Alias -Name Create-EC2PlacementGroup -Value New-EC2PlacementGroup
Set-Alias -Name EC2-CreatePlacementGroup -Value New-EC2PlacementGroup
Set-Alias -Name Create-EC2SecurityGroup -Value New-EC2SecurityGroup
Set-Alias -Name EC2-CreateSecurityGroup -Value New-EC2SecurityGroup
Set-Alias -Name Create-EC2Snapshot -Value New-EC2Snapshot
Set-Alias -Name EC2-CreateSnapshot -Value New-EC2Snapshot
Set-Alias -Name Create-EC2Tags -Value New-EC2Tag
Set-Alias -Name EC2-CreateTags -Value New-EC2Tag
Set-Alias -Name Create-EC2Volume -Value New-EC2Volume
Set-Alias -Name EC2-CreateVolume -Value New-EC2Volume
Set-Alias -Name Deactivate-EC2License -Value Disable-EC2License
Set-Alias -Name EC2-DeactivateLicense -Value Disable-EC2License
Set-Alias -Name Delete-EC2KeyPair -Value Remove-EC2KeyPair
Set-Alias -Name EC2-DeleteKeyPair -Value Remove-EC2KeyPair
Set-Alias -Name Delete-EC2PlacementGroup -Value Remove-EC2PlacementGroup
Set-Alias -Name EC2-DeletePlacementGroup -Value Remove-EC2PlacementGroup
Set-Alias -Name Delete-EC2SecurityGroup -Value Remove-EC2SecurityGroup
Set-Alias -Name EC2-DeleteSecurityGroup -Value Remove-EC2SecurityGroup
Set-Alias -Name Delete-EC2Snapshot -Value Remove-EC2Snapshot
Set-Alias -Name EC2-DeleteSnapshot -Value Remove-EC2Snapshot
Set-Alias -Name Delete-EC2Tags -Value Remove-EC2Tag
Set-Alias -Name EC2-DeleteTags -Value Remove-EC2Tag
Set-Alias -Name Delete-EC2Volume -Value Remove-EC2Volume
Set-Alias -Name EC2-DeleteVolume -Value Remove-EC2Volume
Set-Alias -Name Deregister-EC2Image -Value Unregister-EC2Image
Set-Alias -Name EC2-DeregisterImage -Value Unregister-EC2Image
Set-Alias -Name Describe-EC2Addresses -Value Get-EC2Address
Set-Alias -Name EC2-DescribeAddresses -Value Get-EC2Address
Set-Alias -Name Describe-EC2AvailabilityZones -Value Get-EC2AvailabilityZone
Set-Alias -Name EC2-DescribeAvailabilityZones -Value Get-EC2AvailabilityZone
Set-Alias -Name Describe-EC2BundleTasks -Value Get-EC2BundleTask
Set-Alias -Name EC2-DescribeBundleTasks -Value Get-EC2BundleTask
Set-Alias -Name Describe-EC2Licenses -Value Get-EC2License
Set-Alias -Name EC2-DescribeLicenses -Value Get-EC2License
Set-Alias -Name Describe-EC2PlacementGroups -Value Get-EC2PlacementGroup
Set-Alias -Name EC2-DescribePlacementGroups -Value Get-EC2PlacementGroup
Set-Alias -Name Describe-EC2SnapshotAttribute -Value Get-EC2SnapshotAttribute
Set-Alias -Name EC2-DescribeSnapshotAttribute -Value Get-EC2SnapshotAttribute
Set-Alias -Name Describe-EC2ImageAttribute -Value Get-EC2ImageAttribute
Set-Alias -Name EC2-DescribeImageAttribute -Value Get-EC2ImageAttribute
Set-Alias -Name Describe-EC2Images -Value Get-EC2Image
Set-Alias -Name EC2-DescribeImages -Value Get-EC2Image
Set-Alias -Name Describe-EC2InstanceStatus -Value Get-EC2InstanceStatus
Set-Alias -Name EC2-DescribeInstanceStatus -Value Get-EC2InstanceStatus
Set-Alias -Name Report-EC2InstanceStatus -Value Send-EC2InstanceStatus
Set-Alias -Name EC2-ReportInstanceStatus -Value Send-EC2InstanceStatus
Set-Alias -Name Describe-EC2Regions -Value Get-EC2Region
Set-Alias -Name EC2-DescribeRegions -Value Get-EC2Region
Set-Alias -Name Describe-EC2ReservedInstances -Value Get-EC2ReservedInstance
Set-Alias -Name EC2-DescribeReservedInstances -Value Get-EC2ReservedInstance
Set-Alias -Name Describe-EC2ReservedInstancesOfferings -Value Get-EC2ReservedInstancesOffering
Set-Alias -Name EC2-DescribeReservedInstancesOfferings -Value Get-EC2ReservedInstancesOffering
Set-Alias -Name Describe-EC2KeyPairs -Value Get-EC2KeyPair
Set-Alias -Name EC2-DescribeKeyPairs -Value Get-EC2KeyPair
Set-Alias -Name Describe-EC2SecurityGroups -Value Get-EC2SecurityGroup
Set-Alias -Name EC2-DescribeSecurityGroups -Value Get-EC2SecurityGroup
Set-Alias -Name Describe-EC2Snapshots -Value Get-EC2Snapshot
Set-Alias -Name EC2-DescribeSnapshots -Value Get-EC2Snapshot
Set-Alias -Name Describe-EC2Tags -Value Get-EC2Tag
Set-Alias -Name EC2-DescribeTags -Value Get-EC2Tag
Set-Alias -Name Describe-EC2Volumes -Value Get-EC2Volume
Set-Alias -Name EC2-DescribeVolumes -Value Get-EC2Volume
Set-Alias -Name Detach-EC2Volume -Value Dismount-EC2Volume
Set-Alias -Name EC2-DetachVolume -Value Dismount-EC2Volume
Set-Alias -Name Disassociate-EC2Address -Value Unregister-EC2Address
Set-Alias -Name EC2-DisassociateAddress -Value Unregister-EC2Address
Set-Alias -Name EC2-GetPasswordData -Value Get-EC2PasswordData
Set-Alias -Name EC2-GetConsoleOutput -Value Get-EC2ConsoleOutput
Set-Alias -Name EC2-ImportKeyPair -Value Import-EC2KeyPair
Set-Alias -Name Modify-EC2SnapshotAttribute -Value Edit-EC2SnapshotAttribute
Set-Alias -Name EC2-ModifySnapshotAttribute -Value Edit-EC2SnapshotAttribute
Set-Alias -Name Modify-EC2ImageAttribute -Value Edit-EC2ImageAttribute
Set-Alias -Name EC2-ModifyImageAttribute -Value Edit-EC2ImageAttribute
Set-Alias -Name EC2-PurchaseReservedInstancesOffering -Value New-EC2ReservedInstance
Set-Alias -Name Reboot-EC2Instances -Value Restart-EC2Instance
Set-Alias -Name EC2-RebootInstances -Value Restart-EC2Instance
Set-Alias -Name EC2-RegisterImage -Value Register-EC2Image
Set-Alias -Name Release-EC2Address -Value Remove-EC2Address
Set-Alias -Name EC2-ReleaseAddress -Value Remove-EC2Address
Set-Alias -Name EC2-ResetSnapshotAttribute -Value Reset-EC2SnapshotAttribute
Set-Alias -Name EC2-ResetImageAttribute -Value Reset-EC2ImageAttribute
Set-Alias -Name EC2-RevokeSecurityGroupIngress -Value Revoke-EC2SecurityGroupIngress
Set-Alias -Name Run-EC2Instances -Value New-EC2Instance
Set-Alias -Name EC2-RunInstances -Value New-EC2Instance
Set-Alias -Name Start-EC2Instances -Value Start-EC2Instance
Set-Alias -Name EC2-StartInstances -Value Start-EC2Instance
Set-Alias -Name Modify-EC2InstanceAttribute -Value Edit-EC2InstanceAttribute
Set-Alias -Name EC2-ModifyInstanceAttribute -Value Edit-EC2InstanceAttribute
Set-Alias -Name EC2-ResetInstanceAttribute -Value Reset-EC2InstanceAttribute
Set-Alias -Name Describe-EC2InstanceAttribute -Value Get-EC2InstanceAttribute
Set-Alias -Name EC2-DescribeInstanceAttribute -Value Get-EC2InstanceAttribute
Set-Alias -Name EC2-MonitorInstances -Value Start-EC2InstanceMonitoring
Set-Alias -Name EC2-UnmonitorInstances -Value Stop-EC2InstanceMonitoring
Set-Alias -Name Describe-EC2VpnConnections -Value Get-EC2VpnConnection
Set-Alias -Name EC2-DescribeVpnConnections -Value Get-EC2VpnConnection
Set-Alias -Name Describe-EC2Subnets -Value Get-EC2Subnet
Set-Alias -Name EC2-DescribeSubnets -Value Get-EC2Subnet
Set-Alias -Name Detach-EC2VpnGateway -Value Dismount-EC2VpnGateway
Set-Alias -Name EC2-DetachVpnGateway -Value Dismount-EC2VpnGateway
Set-Alias -Name Describe-EC2Vpcs -Value Get-EC2Vpc
Set-Alias -Name EC2-DescribeVpcs -Value Get-EC2Vpc
Set-Alias -Name Delete-EC2CustomerGateway -Value Remove-EC2CustomerGateway
Set-Alias -Name EC2-DeleteCustomerGateway -Value Remove-EC2CustomerGateway
Set-Alias -Name Attach-EC2VpnGateway -Value Add-EC2VpnGateway
Set-Alias -Name EC2-AttachVpnGateway -Value Add-EC2VpnGateway
Set-Alias -Name Delete-EC2DhcpOptions -Value Remove-EC2DhcpOption
Set-Alias -Name EC2-DeleteDhcpOptions -Value Remove-EC2DhcpOption
Set-Alias -Name Delete-EC2Subnet -Value Remove-EC2Subnet
Set-Alias -Name EC2-DeleteSubnet -Value Remove-EC2Subnet
Set-Alias -Name Create-EC2Vpc -Value New-EC2Vpc
Set-Alias -Name EC2-CreateVpc -Value New-EC2Vpc
Set-Alias -Name Create-EC2CustomerGateway -Value New-EC2CustomerGateway
Set-Alias -Name EC2-CreateCustomerGateway -Value New-EC2CustomerGateway
Set-Alias -Name Create-EC2VpnGateway -Value New-EC2VpnGateway
Set-Alias -Name EC2-CreateVpnGateway -Value New-EC2VpnGateway
Set-Alias -Name Delete-EC2Vpc -Value Remove-EC2Vpc
Set-Alias -Name EC2-DeleteVpc -Value Remove-EC2Vpc
Set-Alias -Name Associate-EC2DhcpOptions -Value Register-EC2DhcpOption
Set-Alias -Name EC2-AssociateDhcpOptions -Value Register-EC2DhcpOption
Set-Alias -Name Describe-EC2VpnGateways -Value Get-EC2VpnGateway
Set-Alias -Name EC2-DescribeVpnGateways -Value Get-EC2VpnGateway
Set-Alias -Name Create-EC2Subnet -Value New-EC2Subnet
Set-Alias -Name EC2-CreateSubnet -Value New-EC2Subnet
Set-Alias -Name Delete-EC2VpnConnection -Value Remove-EC2VpnConnection
Set-Alias -Name EC2-DeleteVpnConnection -Value Remove-EC2VpnConnection
Set-Alias -Name Delete-EC2VpnGateway -Value Remove-EC2VpnGateway
Set-Alias -Name EC2-DeleteVpnGateway -Value Remove-EC2VpnGateway
Set-Alias -Name Describe-EC2CustomerGateways -Value Get-EC2CustomerGateway
Set-Alias -Name EC2-DescribeCustomerGateways -Value Get-EC2CustomerGateway
Set-Alias -Name Create-EC2VpnConnection -Value New-EC2VpnConnection
Set-Alias -Name EC2-CreateVpnConnection -Value New-EC2VpnConnection
Set-Alias -Name Describe-EC2DhcpOptions -Value Get-EC2DhcpOption
Set-Alias -Name EC2-DescribeDhcpOptions -Value Get-EC2DhcpOption
Set-Alias -Name EC2-StopInstance -Value Stop-EC2Instance
Set-Alias -Name EC-AuthorizeCacheSecurityGroupIngress -Value Approve-ECCacheSecurityGroupIngress
Set-Alias -Name Authorize-ECCacheSecurityGroupIngress -Value Approve-ECCacheSecurityGroupIngress
Set-Alias -Name EC-CreateCacheSubnetGroup -Value New-ECCacheSubnetGroup
Set-Alias -Name EC-PurchaseReservedCacheNodesOffering -Value Request-ECReservedCacheNodesOffering
Set-Alias -Name Purchase-ECReservedCacheNodesOffering -Value Request-ECReservedCacheNodesOffering
Set-Alias -Name EC-RebootCacheCluster -Value Restart-ECCacheCluster
Set-Alias -Name Reboot-ECCacheCluster -Value Restart-ECCacheCluster
Set-Alias -Name EC-RevokeCacheSecurityGroupIngress -Value Revoke-ECCacheSecurityGroupIngress
Set-Alias -Name EC-DescribeCacheSubnetGroups -Value Get-ECCacheSubnetGroups
Set-Alias -Name EC-CreateCacheSecurityGroup -Value New-ECCacheSecurityGroup
Set-Alias -Name EC-CreateCacheCluster -Value New-ECCacheCluster
Set-Alias -Name EC-DescribeEvents -Value Get-ECEvent
Set-Alias -Name EC-DescribeReservedCacheNodes -Value Get-ECReservedCacheNode
Set-Alias -Name EC-DescribeCacheEngineVersions -Value Get-ECCacheEngineVersions
Set-Alias -Name EC-DeleteCacheParameterGroup -Value Remove-ECCacheParameterGroup
Set-Alias -Name EC-ModifyCacheParameterGroup -Value Edit-ECCacheParameterGroup
Set-Alias -Name EC-DescribeEngineDefaultParameters -Value Get-ECEngineDefaultParameter
Set-Alias -Name EC-DeleteCacheSubnetGroup -Value Remove-ECCacheSubnetGroup
Set-Alias -Name EC-CreateCacheParameterGroup -Value New-ECCacheParameterGroup
Set-Alias -Name EC-DescribeCacheSecurityGroups -Value Get-ECCacheSecurityGroup
Set-Alias -Name EC-DescribeCacheParameterGroups -Value Get-ECCacheParameterGroup
Set-Alias -Name EC-DescribeCacheClusters -Value Get-ECCacheCluster
Set-Alias -Name EC-ResetCacheParameterGroup -Value Reset-ECCacheParameterGroup
Set-Alias -Name EC-DeleteCacheSecurityGroup -Value Remove-ECCacheSecurityGroup
Set-Alias -Name EC-ModifyCacheCluster -Value Edit-ECCacheCluster
Set-Alias -Name EC-DeleteCacheCluster -Value Remove-ECCacheCluster
Set-Alias -Name EC-DescribeReservedCacheNodesOfferings -Value Get-ECReservedCacheNodesOffering
Set-Alias -Name EC-DescribeCacheParameters -Value Get-ECCacheParameter
Set-Alias -Name EC-ModifyCacheSubnetGroup -Value Edit-ECCacheSubnetGroup
Set-Alias -Name ELB-DescribeLoadBalancerPolicyTypes -Value Get-ELBLoadBalancerPolicyType
Set-Alias -Name ELB-ConfigureHealthCheck -Value Set-ELBHealthCheck
Set-Alias -Name ELB-DetachLoadBalancerFromSubnets -Value Dismount-ELBLoadBalancerFromSubnet
Set-Alias -Name ELB-DescribeLoadBalancerPolicies -Value Get-ELBLoadBalancerPolicy
Set-Alias -Name ELB-SetLoadBalancerPoliciesOfListener -Value Set-ELBLoadBalancerPolicyOfListener
Set-Alias -Name ELB-DisableAvailabilityZonesForLoadBalancer -Value Disable-ELBAvailabilityZoneForLoadBalancer
Set-Alias -Name ELB-DescribeInstanceHealth -Value Get-ELBInstanceHealth
Set-Alias -Name ELB-DeleteLoadBalancerPolicy -Value Remove-ELBLoadBalancerPolicy
Set-Alias -Name ELB-CreateLoadBalancerPolicy -Value New-ELBLoadBalancerPolicy
Set-Alias -Name ELB-EnableAvailabilityZonesForLoadBalancer -Value Enable-ELBAvailabilityZoneForLoadBalancer
Set-Alias -Name ELB-CreateLoadBalancerListeners -Value New-ELBLoadBalancerListener
Set-Alias -Name ELB-CreateLoadBalancer -Value New-ELBLoadBalancer
Set-Alias -Name ELB-DeleteLoadBalancer -Value Remove-ELBLoadBalancer
Set-Alias -Name ELB-SetLoadBalancerPoliciesForBackendServer -Value Set-ELBLoadBalancerPolicyForBackendServer
Set-Alias -Name ELB-DeleteLoadBalancerListeners -Value Remove-ELBLoadBalancerListener
Set-Alias -Name ELB-DeregisterInstancesFromLoadBalancer -Value Remove-ELBInstanceFromLoadBalancer
Set-Alias -Name ELB-SetLoadBalancerListenerSSLCertificate -Value Set-ELBLoadBalancerListenerSSLCertificate
Set-Alias -Name ELB-CreateLBCookieStickinessPolicy -Value New-ELBLBCookieStickinessPolicy
Set-Alias -Name ELB-AttachLoadBalancerToSubnets -Value Add-ELBLoadBalancerToSubnet
Set-Alias -Name ELB-CreateAppCookieStickinessPolicy -Value New-ELBAppCookieStickinessPolicy
Set-Alias -Name ELB-RegisterInstancesWithLoadBalancer -Value Register-ELBInstanceWithLoadBalancer
Set-Alias -Name ELB-ApplySecurityGroupsToLoadBalancer -Value Join-ELBSecurityGroupToLoadBalancer
Set-Alias -Name ELB-DescribeLoadBalancers -Value Get-ELBLoadBalancer
Set-Alias -Name EMR-SetVisibleToAllUsers -Value Set-EMRVisibleToAllUsers
Set-Alias -Name EMR-AddInstanceGroups -Value Add-EMRInstanceGroup
Set-Alias -Name EMR-AddJobFlowSteps -Value Add-EMRJobFlowStep
Set-Alias -Name EMR-TerminateJobFlows -Value Stop-EMRJobFlow
Set-Alias -Name EMR-DescribeJobFlows -Value Get-EMRJobFlow
Set-Alias -Name EMR-SetTerminationProtection -Value Set-EMRTerminationProtection
Set-Alias -Name EMR-RunJobFlow -Value Start-EMRJobFlow
Set-Alias -Name EMR-ModifyInstanceGroups -Value Edit-EMRInstanceGroup
Set-Alias -Name ETS-DeletePipeline -Value Remove-ETSPipeline
Set-Alias -Name ETS-CancelJob -Value Stop-ETSJob
Set-Alias -Name ETS-ListPresets -Value Get-ETSPreset
Set-Alias -Name ETS-ListJobsByStatus -Value Get-ETSJobsByStatus
Set-Alias -Name ETS-CreatePipeline -Value New-ETSPipeline
Set-Alias -Name ETS-TestRole -Value Test-ETSRole
Set-Alias -Name ETS-ListPipelines -Value Get-ETSPipeline
Set-Alias -Name ETS-UpdatePipelineNotifications -Value Update-ETSPipelineNotifications
Set-Alias -Name ETS-ListJobsByPipeline -Value Get-ETSJobsByPipeline
Set-Alias -Name ETS-CreateJob -Value New-ETSJob
Set-Alias -Name ETS-UpdatePipelineStatus -Value Update-ETSPipelineStatus
Set-Alias -Name ETS-ReadPipeline -Value Read-ETSPipeline
Set-Alias -Name ETS-ReadJob -Value Read-ETSJob
Set-Alias -Name ETS-DeletePreset -Value Remove-ETSPreset
Set-Alias -Name ETS-CreatePreset -Value New-ETSPreset
Set-Alias -Name ETS-ReadPreset -Value Read-ETSPreset
Set-Alias -Name IAM-AddRoleToInstanceProfile -Value Add-IAMRoleToInstanceProfile
Set-Alias -Name IAM-GetGroupPolicy -Value Get-IAMGroupPolicy
Set-Alias -Name IAM-GetRolePolicy -Value Get-IAMRolePolicy
Set-Alias -Name IAM-ListInstanceProfilesForRole -Value Get-IAMInstanceProfileForRole
Set-Alias -Name IAM-ListVirtualMFADevices -Value Get-IAMVirtualMFADevice
Set-Alias -Name IAM-DeleteRolePolicy -Value Remove-IAMRolePolicy
Set-Alias -Name IAM-CreateInstanceProfile -Value New-IAMInstanceProfile
Set-Alias -Name IAM-ListGroupPolicies -Value Get-IAMGroupPolicies
Set-Alias -Name IAM-CreateLoginProfile -Value New-IAMLoginProfile
Set-Alias -Name IAM-RemoveRoleFromInstanceProfile -Value Remove-IAMRoleFromInstanceProfile
Set-Alias -Name IAM-UpdateAccountPasswordPolicy -Value Update-IAMAccountPasswordPolicy
Set-Alias -Name IAM-UpdateAssumeRolePolicy -Value Update-IAMAssumeRolePolicy
Set-Alias -Name IAM-GetInstanceProfile -Value Get-IAMInstanceProfile
Set-Alias -Name IAM-ListRoles -Value Get-IAMRoles
Set-Alias -Name IAM-GetAccountSummary -Value Get-IAMAccountSummary
Set-Alias -Name IAM-GetAccountPasswordPolicy -Value Get-IAMAccountPasswordPolicy
Set-Alias -Name IAM-CreateAccessKey -Value New-IAMAccessKey
Set-Alias -Name IAM-GetUser -Value Get-IAMUser
Set-Alias -Name IAM-ResyncMFADevice -Value Sync-IAMMFADevice
Set-Alias -Name IAM-ListMFADevices -Value Get-IAMMFADevice
Set-Alias -Name IAM-CreateVirtualMFADevice -Value New-IAMVirtualMFADevice
Set-Alias -Name IAM-ListInstanceProfiles -Value Get-IAMInstanceProfiles
Set-Alias -Name IAM-UpdateAccessKey -Value Update-IAMAccessKey
Set-Alias -Name IAM-AddUserToGroup -Value Add-IAMUserToGroup
Set-Alias -Name IAM-GetGroup -Value Get-IAMGroup
Set-Alias -Name IAM-ListAccountAliases -Value Get-IAMAccountAlias
Set-Alias -Name IAM-DeleteGroup -Value Remove-IAMGroup
Set-Alias -Name IAM-GetRole -Value Get-IAMRole
Set-Alias -Name IAM-ListRolePolicies -Value Get-IAMRolePolicies
Set-Alias -Name IAM-ListSigningCertificates -Value Get-IAMSigningCertificate
Set-Alias -Name IAM-UploadSigningCertificate -Value Publish-IAMSigningCertificate
Set-Alias -Name IAM-DeleteInstanceProfile -Value Remove-IAMInstanceProfile
Set-Alias -Name IAM-CreateRole -Value New-IAMRole
Set-Alias -Name IAM-UpdateLoginProfile -Value Update-IAMLoginProfile
Set-Alias -Name IAM-DeleteLoginProfile -Value Remove-IAMLoginProfile
Set-Alias -Name IAM-ChangePassword -Value Edit-IAMPassword
Set-Alias -Name IAM-GetServerCertificate -Value Get-IAMServerCertificate
Set-Alias -Name IAM-PutGroupPolicy -Value Write-IAMGroupPolicy
Set-Alias -Name IAM-DeleteSigningCertificate -Value Remove-IAMSigningCertificate
Set-Alias -Name IAM-ListUserPolicies -Value Get-IAMUserPolicies
Set-Alias -Name IAM-ListAccessKeys -Value Get-IAMAccessKey
Set-Alias -Name IAM-ListGroupsForUser -Value Get-IAMGroupForUser
Set-Alias -Name IAM-DeleteAccountAlias -Value Remove-IAMAccountAlias
Set-Alias -Name IAM-ListGroups -Value Get-IAMGroups
Set-Alias -Name IAM-DeleteAccessKey -Value Remove-IAMAccessKey
Set-Alias -Name IAM-DeleteVirtualMFADevice -Value Remove-IAMVirtualMFADevice
Set-Alias -Name IAM-DeleteUserPolicy -Value Remove-IAMUserPolicy
Set-Alias -Name IAM-PutUserPolicy -Value Write-IAMUserPolicy
Set-Alias -Name IAM-ListServerCertificates -Value Get-IAMServerCertificates
Set-Alias -Name IAM-GetUserPolicy -Value Get-IAMUserPolicy
Set-Alias -Name IAM-UpdateServerCertificate -Value Update-IAMServerCertificate
Set-Alias -Name IAM-UpdateUser -Value Update-IAMUser
Set-Alias -Name IAM-PutRolePolicy -Value Write-IAMRolePolicy
Set-Alias -Name IAM-UpdateSigningCertificate -Value Update-IAMSigningCertificate
Set-Alias -Name IAM-DeleteGroupPolicy -Value Remove-IAMGroupPolicy
Set-Alias -Name IAM-ListUsers -Value Get-IAMUsers
Set-Alias -Name IAM-UpdateGroup -Value Update-IAMGroup
Set-Alias -Name IAM-CreateUser -Value New-IAMUser
Set-Alias -Name IAM-EnableMFADevice -Value Enable-IAMMFADevice
Set-Alias -Name IAM-DeleteAccountPasswordPolicy -Value Remove-IAMAccountPasswordPolicy
Set-Alias -Name IAM-GetLoginProfile -Value Get-IAMLoginProfile
Set-Alias -Name IAM-UploadServerCertificate -Value Publish-IAMServerCertificate
Set-Alias -Name IAM-CreateGroup -Value New-IAMGroup
Set-Alias -Name IAM-CreateAccountAlias -Value New-IAMAccountAlias
Set-Alias -Name IAM-DeleteUser -Value Remove-IAMUser
Set-Alias -Name IAM-DeactivateMFADevice -Value Disable-IAMMFADevice
Set-Alias -Name IAM-RemoveUserFromGroup -Value Remove-IAMUserFromGroup
Set-Alias -Name IAM-DeleteRole -Value Remove-IAMRole
Set-Alias -Name IAM-DeleteServerCertificate -Value Remove-IAMServerCertificate
Set-Alias -Name Create-IEJob -Value New-IEJob
Set-Alias -Name IE-CreateJob -Value New-IEJob
Set-Alias -Name Cancel-IEJob -Value Stop-IEJob
Set-Alias -Name IE-CancelJob -Value Stop-IEJob
Set-Alias -Name IE-GetStatus -Value Get-IEStatus
Set-Alias -Name List-IEJobs -Value Get-IEJob
Set-Alias -Name IE-ListJobs -Value Get-IEJob
Set-Alias -Name IE-UpdateJob -Value Update-IEJob
Set-Alias -Name OPS-DescribeDeployments -Value Get-OPSDeployments
Set-Alias -Name OPS-UpdateLayer -Value Update-OPSLayer
Set-Alias -Name OPS-StartInstance -Value Start-OPSInstance
Set-Alias -Name OPS-DescribeElasticIps -Value Get-OPSElasticIps
Set-Alias -Name OPS-DescribeStacks -Value Get-OPSStacks
Set-Alias -Name OPS-DescribeApps -Value Get-OPSApps
Set-Alias -Name OPS-CreateLayer -Value New-OPSLayer
Set-Alias -Name OPS-DeleteStack -Value Remove-OPSStack
Set-Alias -Name OPS-StartStack -Value Start-OPSStack
Set-Alias -Name OPS-StopStack -Value Stop-OPSStack
Set-Alias -Name OPS-CreateDeployment -Value New-OPSDeployment
Set-Alias -Name OPS-UpdateUserProfile -Value Update-OPSUserProfile
Set-Alias -Name OPS-RebootInstance -Value Restart-OPSInstance
Set-Alias -Name Reboot-OPSInstance -Value Restart-OPSInstance
Set-Alias -Name OPS-SetPermission -Value Set-OPSPermission
Set-Alias -Name OPS-DescribeInstances -Value Get-OPSInstances
Set-Alias -Name OPS-DescribePermissions -Value Get-OPSPermissions
Set-Alias -Name OPS-DeleteInstance -Value Remove-OPSInstance
Set-Alias -Name OPS-CreateInstance -Value New-OPSInstance
Set-Alias -Name OPS-StopInstance -Value Stop-OPSInstance
Set-Alias -Name OPS-UpdateApp -Value Update-OPSApp
Set-Alias -Name OPS-DeleteApp -Value Remove-OPSApp
Set-Alias -Name OPS-DescribeCommands -Value Get-OPSCommands
Set-Alias -Name OPS-UpdateStack -Value Update-OPSStack
Set-Alias -Name OPS-CreateUserProfile -Value New-OPSUserProfile
Set-Alias -Name OPS-GetHostnameSuggestion -Value Get-OPSHostnameSuggestion
Set-Alias -Name OPS-DescribeRaidArrays -Value Get-OPSRaidArrays
Set-Alias -Name OPS-DescribeLayers -Value Get-OPSLayers
Set-Alias -Name OPS-DescribeLoadBasedAutoScaling -Value Get-OPSLoadBasedAutoScaling
Set-Alias -Name OPS-SetLoadBasedAutoScaling -Value Set-OPSLoadBasedAutoScaling
Set-Alias -Name OPS-DeleteLayer -Value Remove-OPSLayer
Set-Alias -Name OPS-DescribeVolumes -Value Get-OPSVolumes
Set-Alias -Name OPS-SetTimeBasedAutoScaling -Value Set-OPSTimeBasedAutoScaling
Set-Alias -Name OPS-CreateApp -Value New-OPSApp
Set-Alias -Name OPS-DescribeTimeBasedAutoScaling -Value Get-OPSTimeBasedAutoScaling
Set-Alias -Name OPS-DeleteUserProfile -Value Remove-OPSUserProfile
Set-Alias -Name OPS-DescribeUserProfiles -Value Get-OPSUserProfiles
Set-Alias -Name OPS-UpdateInstance -Value Update-OPSInstance
Set-Alias -Name OPS-DescribeServiceErrors -Value Get-OPSServiceErrors
Set-Alias -Name Clone-OPSStack -Value Copy-OPSStack
Set-Alias -Name Describe-RDSEventCategories -Value Get-RDSEventCategories
Set-Alias -Name RDS-DescribeEventCategories -Value Get-RDSEventCategories
Set-Alias -Name Delete-RDSDBParameterGroup -Value Remove-RDSDBParameterGroup
Set-Alias -Name RDS-DeleteDBParameterGroup -Value Remove-RDSDBParameterGroup
Set-Alias -Name Create-RDSEventSubscription -Value New-RDSEventSubscription
Set-Alias -Name RDS-CreateEventSubscription -Value New-RDSEventSubscription
Set-Alias -Name RDS-CopyDBSnapshot -Value Copy-RDSDBSnapshot
Set-Alias -Name Create-RDSDBSubnetGroup -Value New-RDSDBSubnetGroup
Set-Alias -Name RDS-CreateDBSubnetGroup -Value New-RDSDBSubnetGroup
Set-Alias -Name Describe-RDSDBSubnetGroups -Value Get-RDSDBSubnetGroup
Set-Alias -Name RDS-DescribeDBSubnetGroups -Value Get-RDSDBSubnetGroup
Set-Alias -Name Delete-RDSEventSubscription -Value Remove-RDSEventSubscription
Set-Alias -Name RDS-DeleteEventSubscription -Value Remove-RDSEventSubscription
Set-Alias -Name RDS-AuthorizeDBSecurityGroupIngress -Value Enable-RDSDBSecurityGroupIngress
Set-Alias -Name Modify-RDSDBSubnetGroup -Value Edit-RDSDBSubnetGroup
Set-Alias -Name RDS-ModifyDBSubnetGroup -Value Edit-RDSDBSubnetGroup
Set-Alias -Name RDS-AddSourceIdentifierToSubscription -Value Add-RDSSourceIdentifierToSubscription
Set-Alias -Name Delete-RDSDBSecurityGroup -Value Remove-RDSDBSecurityGroup
Set-Alias -Name RDS-DeleteDBSecurityGroup -Value Remove-RDSDBSecurityGroup
Set-Alias -Name RDS-RestoreDBInstanceFromDBSnapshot -Value Restore-RDSDBInstanceFromDBSnapshot
Set-Alias -Name Describe-RDSOptionGroupOptions -Value Get-RDSOptionGroupOption
Set-Alias -Name RDS-DescribeOptionGroupOptions -Value Get-RDSOptionGroupOption
Set-Alias -Name Describe-RDSDBEngineVersions -Value Get-RDSDBEngineVersion
Set-Alias -Name RDS-DescribeDBEngineVersions -Value Get-RDSDBEngineVersion
Set-Alias -Name Modify-RDSDBParameterGroup -Value Edit-RDSDBParameterGroup
Set-Alias -Name RDS-ModifyDBParameterGroup -Value Edit-RDSDBParameterGroup
Set-Alias -Name Delete-RDSDBInstance -Value Remove-RDSDBInstance
Set-Alias -Name RDS-DeleteDBInstance -Value Remove-RDSDBInstance
Set-Alias -Name RDS-AddTagsToResource -Value Add-RDSTagsToResource
Set-Alias -Name Describe-RDSDBSnapshots -Value Get-RDSDBSnapshot
Set-Alias -Name RDS-DescribeDBSnapshots -Value Get-RDSDBSnapshot
Set-Alias -Name Describe-RDSEventSubscriptions -Value Get-RDSEventSubscriptions
Set-Alias -Name RDS-DescribeEventSubscriptions -Value Get-RDSEventSubscriptions
Set-Alias -Name Create-RDSDBSnapshot -Value New-RDSDBSnapshot
Set-Alias -Name RDS-CreateDBSnapshot -Value New-RDSDBSnapshot
Set-Alias -Name Describe-RDSOrderableDBInstanceOptions -Value Get-RDSOrderableDBInstanceOption
Set-Alias -Name RDS-DescribeOrderableDBInstanceOptions -Value Get-RDSOrderableDBInstanceOption
Set-Alias -Name Describe-RDSEngineDefaultParameters -Value Get-RDSEngineDefaultParameter
Set-Alias -Name RDS-DescribeEngineDefaultParameters -Value Get-RDSEngineDefaultParameter
Set-Alias -Name Describe-RDSOptionGroups -Value Get-RDSOptionGroup
Set-Alias -Name RDS-DescribeOptionGroups -Value Get-RDSOptionGroup
Set-Alias -Name Delete-RDSDBSnapshot -Value Remove-RDSDBSnapshot
Set-Alias -Name RDS-DeleteDBSnapshot -Value Remove-RDSDBSnapshot
Set-Alias -Name Create-RDSDBInstanceReadReplica -Value New-RDSDBInstanceReadReplica
Set-Alias -Name RDS-CreateDBInstanceReadReplica -Value New-RDSDBInstanceReadReplica
Set-Alias -Name Describe-RDSDBParameterGroups -Value Get-RDSDBParameterGroup
Set-Alias -Name RDS-DescribeDBParameterGroups -Value Get-RDSDBParameterGroup
Set-Alias -Name Describe-RDSEvents -Value Get-RDSEvent
Set-Alias -Name RDS-DescribeEvents -Value Get-RDSEvent
Set-Alias -Name Modify-RDSOptionGroup -Value Edit-RDSOptionGroup
Set-Alias -Name RDS-ModifyOptionGroup -Value Edit-RDSOptionGroup
Set-Alias -Name Create-RDSDBSecurityGroup -Value New-RDSDBSecurityGroup
Set-Alias -Name RDS-CreateDBSecurityGroup -Value New-RDSDBSecurityGroup
Set-Alias -Name Create-RDSDBInstance -Value New-RDSDBInstance
Set-Alias -Name RDS-CreateDBInstance -Value New-RDSDBInstance
Set-Alias -Name Describe-RDSDBParameters -Value Get-RDSDBParameter
Set-Alias -Name RDS-DescribeDBParameters -Value Get-RDSDBParameter
Set-Alias -Name RDS-RestoreDBInstanceToPointInTime -Value Restore-RDSDBInstanceToPointInTime
Set-Alias -Name Create-RDSDBParameterGroup -Value New-RDSDBParameterGroup
Set-Alias -Name RDS-CreateDBParameterGroup -Value New-RDSDBParameterGroup
Set-Alias -Name RDS-ResetDBParameterGroup -Value Reset-RDSDBParameterGroup
Set-Alias -Name Modify-RDSDBInstance -Value Edit-RDSDBInstance
Set-Alias -Name RDS-ModifyDBInstance -Value Edit-RDSDBInstance
Set-Alias -Name RDS-PromoteReadReplica -Value Convert-RDSReadReplicaToStandalone
Set-Alias -Name List-RDSTagsForResource -Value Get-RDSTagForResource
Set-Alias -Name RDS-ListTagsForResource -Value Get-RDSTagForResource
Set-Alias -Name Describe-RDSDBInstances -Value Get-RDSDBInstance
Set-Alias -Name RDS-DescribeDBInstances -Value Get-RDSDBInstance
Set-Alias -Name Describe-RDSDBSecurityGroups -Value Get-RDSDBSecurityGroup
Set-Alias -Name RDS-DescribeDBSecurityGroups -Value Get-RDSDBSecurityGroup
Set-Alias -Name Describe-RDSReservedDBInstances -Value Get-RDSReservedDBInstance
Set-Alias -Name RDS-DescribeReservedDBInstances -Value Get-RDSReservedDBInstance
Set-Alias -Name RDS-RevokeDBSecurityGroupIngress -Value Revoke-RDSDBSecurityGroupIngress
Set-Alias -Name Reboot-RDSDBInstance -Value Restart-RDSDBInstance
Set-Alias -Name RDS-RebootDBInstance -Value Restart-RDSDBInstance
Set-Alias -Name Create-RDSOptionGroup -Value New-RDSOptionGroup
Set-Alias -Name RDS-CreateOptionGroup -Value New-RDSOptionGroup
Set-Alias -Name Describe-RDSReservedDBInstancesOfferings -Value Get-RDSReservedDBInstancesOfferings
Set-Alias -Name RDS-DescribeReservedDBInstancesOfferings -Value Get-RDSReservedDBInstancesOfferings
Set-Alias -Name RDS-PurchaseReservedDBInstancesOffering -Value Get-RDSReservedDBInstancesOffering
Set-Alias -Name Remove-RDSTagsFromResource -Value Remove-RDSTagFromResource
Set-Alias -Name RDS-RemoveTagsFromResource -Value Remove-RDSTagFromResource
Set-Alias -Name Modify-RDSEventSubscription -Value Edit-RDSEventSubscription
Set-Alias -Name RDS-ModifyEventSubscription -Value Edit-RDSEventSubscription
Set-Alias -Name Delete-RDSDBSubnetGroup -Value Remove-RDSDBSubnetGroup
Set-Alias -Name RDS-DeleteDBSubnetGroup -Value Remove-RDSDBSubnetGroup
Set-Alias -Name Delete-RDSOptionGroup -Value Remove-RDSOptionGroup
Set-Alias -Name RDS-DeleteOptionGroup -Value Remove-RDSOptionGroup
Set-Alias -Name RDS-RemoveSourceIdentifierFromSubscription -Value Remove-RDSSourceIdentifierFromSubscription
Set-Alias -Name RS-DescribeClusterParameters -Value Get-RSClusterParameters
Set-Alias -Name RS-RevokeClusterSecurityGroupIngress -Value Revoke-RSClusterSecurityGroupIngress
Set-Alias -Name RS-DescribeClusters -Value Get-RSClusters
Set-Alias -Name RS-DescribeClusterSnapshots -Value Get-RSClusterSnapshots
Set-Alias -Name RS-CreateClusterParameterGroup -Value New-RSClusterParameterGroup
Set-Alias -Name RS-DescribeClusterParameterGroups -Value Get-RSClusterParameterGroups
Set-Alias -Name RS-RestoreFromClusterSnapshot -Value Restore-RSFromClusterSnapshot
Set-Alias -Name RS-ModifyClusterSubnetGroup -Value Edit-RSClusterSubnetGroup
Set-Alias -Name RS-PurchaseReservedNodeOffering -Value Request-RSReservedNodeOffering
Set-Alias -Name RS-ModifyCluster -Value Edit-RSCluster
Set-Alias -Name RS-ModifyClusterParameterGroup -Value Edit-RSClusterParameterGroup
Set-Alias -Name RS-DescribeClusterSecurityGroups -Value Get-RSClusterSecurityGroups
Set-Alias -Name RS-CopyClusterSnapshot -Value Copy-RSClusterSnapshot
Set-Alias -Name RS-DescribeOrderableClusterOptions -Value Get-RSOrderableClusterOptions
Set-Alias -Name RS-CreateClusterSubnetGroup -Value New-RSClusterSubnetGroup
Set-Alias -Name RS-RebootCluster -Value Restart-RSCluster
Set-Alias -Name Reboot-RSCluster -Value Restart-RSCluster
Set-Alias -Name RS-DeleteClusterSubnetGroup -Value Remove-RSClusterSubnetGroup
Set-Alias -Name RS-DescribeClusterSubnetGroups -Value Get-RSClusterSubnetGroups
Set-Alias -Name RS-CreateClusterSnapshot -Value New-RSClusterSnapshot
Set-Alias -Name RS-DeleteCluster -Value Remove-RSCluster
Set-Alias -Name RS-CreateCluster -Value New-RSCluster
Set-Alias -Name RS-DeleteClusterSnapshot -Value Remove-RSClusterSnapshot
Set-Alias -Name RS-DeleteClusterParameterGroup -Value Remove-RSClusterParameterGroup
Set-Alias -Name RS-AuthorizeClusterSecurityGroupIngress -Value Approve-RSClusterSecurityGroupIngress
Set-Alias -Name Authorize-RSClusterSecurityGroupIngress -Value Approve-RSClusterSecurityGroupIngress
Set-Alias -Name RS-DescribeEvents -Value Get-RSEvents
Set-Alias -Name RS-DeleteClusterSecurityGroup -Value Remove-RSClusterSecurityGroup
Set-Alias -Name RS-DescribeReservedNodes -Value Get-RSReservedNodes
Set-Alias -Name RS-ResetClusterParameterGroup -Value Reset-RSClusterParameterGroup
Set-Alias -Name RS-DescribeDefaultClusterParameters -Value Get-RSDefaultClusterParameters
Set-Alias -Name RS-CreateClusterSecurityGroup -Value New-RSClusterSecurityGroup
Set-Alias -Name RS-DescribeReservedNodeOfferings -Value Get-RSReservedNodeOfferings
Set-Alias -Name RS-DescribeResize -Value Get-RSResize
Set-Alias -Name RS-DescribeClusterVersions -Value Get-RSClusterVersions
Set-Alias -Name Purchase-RSReservedNodeOffering -Value Request-ECReservedNodeOffering
Set-Alias -Name R53-ListResourceRecordSets -Value Get-R53ResourceRecordSet
Set-Alias -Name R53-ChangeResourceRecordSets -Value Edit-R53ResourceRecordSet
Set-Alias -Name R53-CreateHostedZone -Value New-R53HostedZone
Set-Alias -Name R53-GetHealthCheck -Value Get-R53HealthCheck
Set-Alias -Name R53-CreateHealthCheck -Value New-R53HealthCheck
Set-Alias -Name R53-GetChange -Value Get-R53Change
Set-Alias -Name R53-DeleteHealthCheck -Value Remove-R53HealthCheck
Set-Alias -Name R53-GetHostedZone -Value Get-R53HostedZone
Set-Alias -Name R53-ListHostedZones -Value Get-R53HostedZones
Set-Alias -Name R53-DeleteHostedZone -Value Remove-R53HostedZone
Set-Alias -Name R53-ListHealthChecks -Value Get-R53HealthChecks
Set-Alias -Name Put-S3BucketWebsite -Value Write-S3BucketWebsite
Set-Alias -Name S3-PutBucketWebsite -Value Write-S3BucketWebsite
Set-Alias -Name S3-GetBucketWebsite -Value Get-S3BucketWebsite
Set-Alias -Name Delete-S3BucketWebsite -Value Remove-S3BucketWebsite
Set-Alias -Name S3-DeleteBucketWebsite -Value Remove-S3BucketWebsite
Set-Alias -Name Put-S3LifecycleConfiguration -Value Write-S3LifecycleConfiguration
Set-Alias -Name S3-PutLifecycleConfiguration -Value Write-S3LifecycleConfiguration
Set-Alias -Name S3-GetLifecycleConfiguration -Value Get-S3LifecycleConfiguration
Set-Alias -Name Delete-S3LifecycleConfiguration -Value Remove-S3LifecycleConfiguration
Set-Alias -Name S3-DeleteLifecycleConfiguration -Value Remove-S3LifecycleConfiguration
Set-Alias -Name Put-S3BucketTagging -Value Write-S3BucketTagging
Set-Alias -Name S3-PutBucketTagging -Value Write-S3BucketTagging
Set-Alias -Name S3-GetBucketTagging -Value Get-S3BucketTagging
Set-Alias -Name Delete-S3BucketTagging -Value Remove-S3BucketTagging
Set-Alias -Name S3-DeleteBucketTagging -Value Remove-S3BucketTagging
Set-Alias -Name Put-S3CORSConfiguration -Value Write-S3CORSConfiguration
Set-Alias -Name S3-PutCORSConfiguration -Value Write-S3CORSConfiguration
Set-Alias -Name S3-GetCORSConfiguration -Value Get-S3CORSConfiguration
Set-Alias -Name Delete-S3CORSConfiguration -Value Remove-S3CORSConfiguration
Set-Alias -Name S3-DeleteCORSConfiguration -Value Remove-S3CORSConfiguration
Set-Alias -Name S3-RestoreObject -Value Restore-S3Object
Set-Alias -Name S3-GetPreSignedURL -Value Get-S3PreSignedURL
Set-Alias -Name S3-GetBucketLocation -Value Get-S3BucketLocation
Set-Alias -Name S3-GetBucketLogging -Value Get-S3BucketLogging
Set-Alias -Name S3-EnableBucketLogging -Value Enable-S3BucketLogging
Set-Alias -Name S3-DisableBucketLogging -Value Disable-S3BucketLogging
Set-Alias -Name S3-GetBucketVersioning -Value Get-S3BucketVersioning
Set-Alias -Name S3-SetBucketVersioning -Value Set-S3BucketVersioning
Set-Alias -Name S3-GetBucketPolicy -Value Get-S3BucketPolicy
Set-Alias -Name Put-S3BucketPolicy -Value Write-S3BucketPolicy
Set-Alias -Name S3-PutBucketPolicy -Value Write-S3BucketPolicy
Set-Alias -Name Delete-S3BucketPolicy -Value Remove-S3BucketPolicy
Set-Alias -Name S3-DeleteBucketPolicy -Value Remove-S3BucketPolicy
Set-Alias -Name S3-SetNotificationConfiguration -Value Set-S3NotificationConfiguration
Set-Alias -Name S3-GetNotificationConfiguration -Value Get-S3NotificationConfiguration
Set-Alias -Name List-S3Versions -Value Get-S3Version
Set-Alias -Name S3-ListVersions -Value Get-S3Version
Set-Alias -Name S3-GetACL -Value Get-S3ACL
Set-Alias -Name Delete-S3Bucket -Value Remove-S3Bucket
Set-Alias -Name S3-DeleteBucket -Value Remove-S3Bucket
Set-Alias -Name S3-GetObjectMetadata -Value Get-S3ObjectMetadata
Set-Alias -Name List-S3Buckets -Value Get-S3Bucket
Set-Alias -Name List-S3Objects -Value Get-S3Object
Set-Alias -Name Get-S3Content -Value Read-S3Object
Set-Alias -Name SES-DeleteIdentity -Value Remove-SESIdentity
Set-Alias -Name SES-ListVerifiedEmailAddresses -Value Get-SESVerifiedEmailAddress
Set-Alias -Name SES-GetSendStatistics -Value Get-SESSendStatistics
Set-Alias -Name SES-VerifyEmailIdentity -Value Confirm-SESEmailIdentity
Set-Alias -Name SES-GetIdentityNotificationAttributes -Value Get-SESIdentityNotificationAttribute
Set-Alias -Name SES-VerifyDomainDkim -Value Confirm-SESDomainDkim
Set-Alias -Name SES-GetIdentityDkimAttributes -Value Get-SESIdentityDkimAttribute
Set-Alias -Name SES-VerifyEmailAddress -Value Confirm-SESEmailAddress
Set-Alias -Name SES-SendRawEmail -Value Send-SESRawEmail
Set-Alias -Name SES-ListIdentities -Value Get-SESIdentity
Set-Alias -Name SES-GetIdentityVerificationAttributes -Value Get-SESIdentityVerificationAttribute
Set-Alias -Name SES-SetIdentityDkimEnabled -Value Set-SESIdentityDkimEnabled
Set-Alias -Name SES-GetSendQuota -Value Get-SESSendQuota
Set-Alias -Name SES-SetIdentityFeedbackForwardingEnabled -Value Set-SESIdentityFeedbackForwardingEnabled
Set-Alias -Name SES-VerifyDomainIdentity -Value Confirm-SESDomainIdentity
Set-Alias -Name SES-SendEmail -Value Send-SESEmail
Set-Alias -Name SES-DeleteVerifiedEmailAddress -Value Remove-SESVerifiedEmailAddress
Set-Alias -Name SES-SetIdentityNotificationTopic -Value Set-SESIdentityNotificationTopic
Set-Alias -Name SNS-ConfirmSubscription -Value Confirm-SNSSubscription
Set-Alias -Name SNS-GetTopicAttributes -Value Get-SNSTopicAttribute
Set-Alias -Name SNS-Subscribe -Value Connect-SNSNotification
Set-Alias -Name SNS-SetTopicAttributes -Value Set-SNSTopicAttribute
Set-Alias -Name SNS-GetSubscriptionAttributes -Value Get-SNSSubscriptionAttribute
Set-Alias -Name SNS-SetSubscriptionAttributes -Value Set-SNSSubscriptionAttribute
Set-Alias -Name SNS-DeleteTopic -Value Remove-SNSTopic
Set-Alias -Name SNS-RemovePermission -Value Remove-SNSPermission
Set-Alias -Name SNS-ListSubscriptions -Value Get-SNSSubscription
Set-Alias -Name SNS-AddPermission -Value Add-SNSPermission
Set-Alias -Name SNS-CreateTopic -Value New-SNSTopic
Set-Alias -Name SNS-ListTopics -Value Get-SNSTopic
Set-Alias -Name SNS-Unsubscribe -Value Disconnect-SNSNotification
Set-Alias -Name SNS-ListSubscriptionsByTopic -Value Get-SNSSubscriptionByTopic
Set-Alias -Name SNS-Publish -Value Publish-SNSMessage
Set-Alias -Name SQS-CreateQueue -Value New-SQSQueue
Set-Alias -Name SQS-ListQueues -Value Get-SQSQueue
Set-Alias -Name SQS-AddPermission -Value Add-SQSPermission
Set-Alias -Name SQS-ChangeMessageVisibility -Value Edit-SQSMessageVisibility
Set-Alias -Name SQS-ChangeMessageVisibilityBatch -Value Edit-SQSMessageVisibilityBatch
Set-Alias -Name SQS-DeleteMessage -Value Remove-SQSMessage
Set-Alias -Name SQS-DeleteMessageBatch -Value Remove-SQSMessageBatch
Set-Alias -Name SQS-DeleteQueue -Value Remove-SQSQueue
Set-Alias -Name SQS-GetQueueAttributes -Value Get-SQSQueueAttribute
Set-Alias -Name SQS-GetQueueUrl -Value Get-SQSQueueUrl
Set-Alias -Name SQS-RemovePermission -Value Remove-SQSPermission
Set-Alias -Name SQS-ReceiveMessage -Value Receive-SQSMessage
Set-Alias -Name SQS-SendMessage -Value Send-SQSMessage
Set-Alias -Name SQS-SendMessageBatch -Value Send-SQSMessageBatch
Set-Alias -Name SQS-SetQueueAttributes -Value Set-SQSQueueAttribute
Set-Alias -Name SG-UpdateChapCredentials -Value Update-SGChapCredentials
Set-Alias -Name SG-AddUploadBuffer -Value Add-SGUploadBuffer
Set-Alias -Name SG-ListVolumeRecoveryPoints -Value Get-SGVolumeRecoveryPoint
Set-Alias -Name SG-DescribeUploadBuffer -Value Get-SGUploadBuffer
Set-Alias -Name SG-AddWorkingStorage -Value Add-SGWorkingStorage
Set-Alias -Name SG-DescribeCachediSCSIVolumes -Value Get-SGCachediSCSIVolume
Set-Alias -Name SG-DescribeGatewayInformation -Value Get-SGGatewayInformation
Set-Alias -Name SG-DeleteBandwidthRateLimit -Value Remove-SGBandwidthRateLimit
Set-Alias -Name SG-ListGateways -Value Get-SGGateway
Set-Alias -Name SG-DeleteChapCredentials -Value Remove-SGChapCredentials
Set-Alias -Name SG-CreateStorediSCSIVolume -Value New-SGStorediSCSIVolume
Set-Alias -Name SG-UpdateGatewayInformation -Value Update-SGGatewayInformation
Set-Alias -Name SG-StartGateway -Value Start-SGGateway
Set-Alias -Name SG-UpdateMaintenanceStartTime -Value Update-SGMaintenanceStartTime
Set-Alias -Name SG-ListVolumes -Value Get-SGVolume
Set-Alias -Name SG-ListLocalDisks -Value Get-SGLocalDisk
Set-Alias -Name SG-DescribeStorediSCSIVolumes -Value Get-SGStorediSCSIVolume
Set-Alias -Name SG-DeleteVolume -Value Remove-SGVolume
Set-Alias -Name SG-DescribeBandwidthRateLimit -Value Get-SGBandwidthRateLimit
Set-Alias -Name SG-DescribeMaintenanceStartTime -Value Get-SGMaintenanceStartTime
Set-Alias -Name SG-CreateSnapshot -Value New-SGSnapshot
Set-Alias -Name SG-DescribeChapCredentials -Value Get-SGChapCredentials
Set-Alias -Name SG-DescribeCache -Value Get-SGCache
Set-Alias -Name SG-DescribeSnapshotSchedule -Value Get-SGSnapshotSchedule
Set-Alias -Name SG-CreateCachediSCSIVolume -Value New-SGCachediSCSIVolume
Set-Alias -Name SG-ShutdownGateway -Value Stop-SGGateway
Set-Alias -Name Shutdown-SGGateway -Value Stop-SGGateway
Set-Alias -Name SG-UpdateGatewaySoftwareNow -Value Update-SGGatewaySoftwareNow
Set-Alias -Name SG-DescribeWorkingStorage -Value Get-SGWorkingStorage
Set-Alias -Name SG-AddCache -Value Add-SGCache
Set-Alias -Name SG-DeleteGateway -Value Remove-SGGateway
Set-Alias -Name SG-CreateSnapshotFromVolumeRecoveryPoint -Value New-SGSnapshotFromVolumeRecoveryPoint
Set-Alias -Name SG-UpdateSnapshotSchedule -Value Update-SGSnapshotSchedule
Set-Alias -Name SG-ActivateGateway -Value Enable-SGGateway
Set-Alias -Name Activate-SGGateway -Value Enable-SGGateway
Set-Alias -Name SG-UpdateBandwidthRateLimit -Value Update-SGBandwidthRateLimit
Set-Alias -Name SG-DeleteSnapshotSchedule -Value Remove-SGSnapshotSchedule
Set-Alias -Name STS-GetSessionToken -Value Get-STSSessionToken
Set-Alias -Name STS-GetFederationToken -Value Get-STSFederationToken
Set-Alias -Name STS-AssumeRole -Value Use-STSRole
Set-Alias -Name Assume-STSRole -Value Use-STSRole
