//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymbolExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalisedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalisedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymbolExplorer.Properties.LocalisedResources", typeof(LocalisedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to:
        ///Shaun, Derek, Dennis, and James.
        ///.
        /// </summary>
        public static string About_Thanks {
            get {
                return ResourceManager.GetString("About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Symbol Explorer.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For updates, and to contribute, see.
        /// </summary>
        public static string About_Updates {
            get {
                return ResourceManager.GetString("About_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://blazingheart.github.io/SymbolExplorer/.
        /// </summary>
        public static string About_URL {
            get {
                return ResourceManager.GetString("About_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string App_Cancel {
            get {
                return ResourceManager.GetString("App_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) 2013-2015 Simon Stevenson.
        /// </summary>
        public static string App_Copyright {
            get {
                return ResourceManager.GetString("App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Explorer.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string App_OK {
            get {
                return ResourceManager.GetString("App_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string EnumText_Separator {
            get {
                return ResourceManager.GetString("EnumText_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive File.
        /// </summary>
        public static string MainWindow_ArchiveFile {
            get {
                return ResourceManager.GetString("MainWindow_ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_GroupFile {
            get {
                return ResourceManager.GetString("MainWindow_GroupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainWindow_GroupView {
            get {
                return ResourceManager.GetString("MainWindow_GroupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header View.
        /// </summary>
        public static string MainWindow_HeaderView {
            get {
                return ResourceManager.GetString("MainWindow_HeaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker Symbols.
        /// </summary>
        public static string MainWindow_LinkerSymbols {
            get {
                return ResourceManager.GetString("MainWindow_LinkerSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object File.
        /// </summary>
        public static string MainWindow_ObjectFile {
            get {
                return ResourceManager.GetString("MainWindow_ObjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_Open {
            get {
                return ResourceManager.GetString("MainWindow_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string MainWindow_Ready {
            get {
                return ResourceManager.GetString("MainWindow_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string MainWindow_Symbols {
            get {
                return ResourceManager.GetString("MainWindow_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_TabHome {
            get {
                return ResourceManager.GetString("MainWindow_TabHome", resourceCulture);
            }
        }
    }
}
